name: sudamericana_validador_identidad
description: "A new Flutter package project."
version: 0.0.1
# homepage:
environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  bloc: ^9.0.0
  camera: ^0.10.5+9  # Versión que usa camera_android por defecto
  camera_android: ^0.10.10+1  # Forzar uso de camera_android para soporte NV21
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.4
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_text_recognition: ^0.15.0
  image: ^4.5.4
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.0.0

dependency_overrides:
  camera_android_camerax: null

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/imagenes/
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fuentes/SFProText-Medium.ttf
          weight: 500
        - asset: assets/fuentes/SFProText-Bold.ttf
          weight: 700
